// AUTO-GENERATED by scripts/generate.ts — do not edit by hand.
// Source: Simple Icons (CC0) — "Gmail" (slug: gmail).
// The trademark belongs to its owner; only the CC0 SVG path is shipped here.
import type { ComponentType } from "react";

const PATH =
  "M24 5.457v13.909c0 .904-.732 1.636-1.636 1.636h-3.819V11.73L12 16.64l-6.545-4.91v9.273H1.636A1.636 1.636 0 0 1 0 19.366V5.457c0-2.023 2.309-3.178 3.927-1.964L5.455 4.64 12 9.548l6.545-4.91 1.528-1.145C21.69 2.28 24 3.434 24 5.457z";

export interface BrandIconProps {
  className?: string;
  size?: number;
}

export const GmailIcon: ComponentType<BrandIconProps> = ({ className, size = 24 }) => (
  <svg
    viewBox="0 0 24 24"
    width={size}
    height={size}
    className={className}
    fill="currentColor"
    role="img"
    aria-hidden="true"
  >
    <path d={PATH} />
  </svg>
);

GmailIcon.displayName = "GmailIcon";
