// AUTO-GENERATED by scripts/generate.ts — do not edit by hand.
import type { ComponentType } from "react";
import type { BrandIconProps } from "./github";
import { GithubIcon } from "./github";
import { XIcon } from "./x";
import { SlackIcon } from "./slack";
import { YoutubeIcon } from "./youtube";
import { StripeIcon } from "./stripe";
import { DiscordIcon } from "./discord";
import { LinkedinIcon } from "./linkedin";
import { GoogleIcon } from "./google";
import { AppleIcon } from "./apple";
import { NpmIcon } from "./npm";
import { NodeIcon } from "./node";
import { ReactIcon } from "./react";
import { TypescriptIcon } from "./typescript";
import { JavascriptIcon } from "./javascript";
import { TailwindIcon } from "./tailwind";
import { LaravelIcon } from "./laravel";
import { PhpIcon } from "./php";
import { VercelIcon } from "./vercel";
import { CloudflareIcon } from "./cloudflare";
import { OpenaiIcon } from "./openai";
import { AnthropicIcon } from "./anthropic";
import { FigmaIcon } from "./figma";
import { NotionIcon } from "./notion";
import { GmailIcon } from "./gmail";

export { GithubIcon } from "./github";
export { XIcon } from "./x";
export { SlackIcon } from "./slack";
export { YoutubeIcon } from "./youtube";
export { StripeIcon } from "./stripe";
export { DiscordIcon } from "./discord";
export { LinkedinIcon } from "./linkedin";
export { GoogleIcon } from "./google";
export { AppleIcon } from "./apple";
export { NpmIcon } from "./npm";
export { NodeIcon } from "./node";
export { ReactIcon } from "./react";
export { TypescriptIcon } from "./typescript";
export { JavascriptIcon } from "./javascript";
export { TailwindIcon } from "./tailwind";
export { LaravelIcon } from "./laravel";
export { PhpIcon } from "./php";
export { VercelIcon } from "./vercel";
export { CloudflareIcon } from "./cloudflare";
export { OpenaiIcon } from "./openai";
export { AnthropicIcon } from "./anthropic";
export { FigmaIcon } from "./figma";
export { NotionIcon } from "./notion";
export { GmailIcon } from "./gmail";
export type { BrandIconProps } from "./github";

export interface BrandIconManifestEntry {
  /** Kebab key the consumer types: <Icon name="github" />. */
  name: string;
  /** Human-readable brand title. */
  title: string;
  /** Originating Simple Icons slug (CC0 source). */
  slug: string;
}

/** Curated marks keyed by the name consumers resolve them under. */
export const curatedMarks: Record<string, ComponentType<BrandIconProps>> = {
  "github": GithubIcon,
  "x": XIcon,
  "slack": SlackIcon,
  "youtube": YoutubeIcon,
  "stripe": StripeIcon,
  "discord": DiscordIcon,
  "linkedin": LinkedinIcon,
  "google": GoogleIcon,
  "apple": AppleIcon,
  "npm": NpmIcon,
  "node": NodeIcon,
  "react": ReactIcon,
  "typescript": TypescriptIcon,
  "javascript": JavascriptIcon,
  "tailwind": TailwindIcon,
  "laravel": LaravelIcon,
  "php": PhpIcon,
  "vercel": VercelIcon,
  "cloudflare": CloudflareIcon,
  "openai": OpenaiIcon,
  "anthropic": AnthropicIcon,
  "figma": FigmaIcon,
  "notion": NotionIcon,
  "gmail": GmailIcon,
};

/** Catalog of every curated mark (for icon pickers, e.g. fancy-cms). */
export const curatedManifest: BrandIconManifestEntry[] = [
  { name: "github", title: "GitHub", slug: "github" },
  { name: "x", title: "X", slug: "x" },
  { name: "slack", title: "Slack", slug: "slack" },
  { name: "youtube", title: "YouTube", slug: "youtube" },
  { name: "stripe", title: "Stripe", slug: "stripe" },
  { name: "discord", title: "Discord", slug: "discord" },
  { name: "linkedin", title: "LinkedIn", slug: "linkedin" },
  { name: "google", title: "Google", slug: "google" },
  { name: "apple", title: "Apple", slug: "apple" },
  { name: "npm", title: "npm", slug: "npm" },
  { name: "node", title: "Node.js", slug: "nodedotjs" },
  { name: "react", title: "React", slug: "react" },
  { name: "typescript", title: "TypeScript", slug: "typescript" },
  { name: "javascript", title: "JavaScript", slug: "javascript" },
  { name: "tailwind", title: "Tailwind CSS", slug: "tailwindcss" },
  { name: "laravel", title: "Laravel", slug: "laravel" },
  { name: "php", title: "PHP", slug: "php" },
  { name: "vercel", title: "Vercel", slug: "vercel" },
  { name: "cloudflare", title: "Cloudflare", slug: "cloudflare" },
  { name: "openai", title: "OpenAI", slug: "openai" },
  { name: "anthropic", title: "Anthropic", slug: "anthropic" },
  { name: "figma", title: "Figma", slug: "figma" },
  { name: "notion", title: "Notion", slug: "notion" },
  { name: "gmail", title: "Gmail", slug: "gmail" },
];
