// AUTO-GENERATED by scripts/generate.ts — do not edit by hand.
// Source: Simple Icons (CC0) — "npm" (slug: npm).
// The trademark belongs to its owner; only the CC0 SVG path is shipped here.
import type { ComponentType } from "react";

const PATH =
  "M1.763 0C.786 0 0 .786 0 1.763v20.474C0 23.214.786 24 1.763 24h20.474c.977 0 1.763-.786 1.763-1.763V1.763C24 .786 23.214 0 22.237 0zM5.13 5.323l13.837.019-.009 13.836h-3.464l.01-10.382h-3.456L12.04 19.17H5.113z";

export interface BrandIconProps {
  className?: string;
  size?: number;
}

export const NpmIcon: ComponentType<BrandIconProps> = ({ className, size = 24 }) => (
  <svg
    viewBox="0 0 24 24"
    width={size}
    height={size}
    className={className}
    fill="currentColor"
    role="img"
    aria-hidden="true"
  >
    <path d={PATH} />
  </svg>
);

NpmIcon.displayName = "NpmIcon";
