// AUTO-GENERATED by scripts/generate.ts — do not edit by hand.
// Source: Simple Icons (CC0) — "Vercel" (slug: vercel).
// The trademark belongs to its owner; only the CC0 SVG path is shipped here.
import type { ComponentType } from "react";

const PATH =
  "M24 22.525H0l12-21.05 12 21.05z";

export interface BrandIconProps {
  className?: string;
  size?: number;
}

export const VercelIcon: ComponentType<BrandIconProps> = ({ className, size = 24 }) => (
  <svg
    viewBox="0 0 24 24"
    width={size}
    height={size}
    className={className}
    fill="currentColor"
    role="img"
    aria-hidden="true"
  >
    <path d={PATH} />
  </svg>
);

VercelIcon.displayName = "VercelIcon";
