/**
 * Brand-icon generator.
 *
 * Reads CC0 SVG path data from `simple-icons` (a BUILD-TIME devDependency only)
 * and emits one self-contained React component per curated mark into
 * `src/marks/`, with the SVG `d` attribute INLINED as a string literal. The
 * generated output therefore has ZERO runtime dependency on simple-icons — the
 * paths are baked into source. Re-run with `npm run gen` to refresh.
 *
 * Curated key  ->  simple-icons slug
 * The key is the clean kebab name consumers type: `<Icon name="github" />`.
 */
import { mkdirSync, writeFileSync, rmSync, existsSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import * as simpleIcons from "simple-icons";

const __dirname = dirname(fileURLToPath(import.meta.url));
const MARKS_DIR = join(__dirname, "..", "src", "marks");

/** key (what the consumer types) -> simple-icons slug (CC0 source). */
const CURATED: Record<string, string> = {
  github: "github",
  x: "x",
  slack: "slack",
  youtube: "youtube",
  stripe: "stripe",
  discord: "discord",
  linkedin: "linkedin",
  google: "google",
  apple: "apple",
  npm: "npm",
  node: "nodedotjs",
  react: "react",
  typescript: "typescript",
  javascript: "javascript",
  tailwind: "tailwindcss",
  laravel: "laravel",
  php: "php",
  vercel: "vercel",
  cloudflare: "cloudflare",
  openai: "openai",
  anthropic: "anthropic",
  figma: "figma",
  notion: "notion",
  gmail: "gmail",
};

type SiIcon = { title: string; slug: string; path: string };

function slugToExport(slug: string): string {
  // simple-icons named exports: "si" + PascalCase of the slug.
  // Slugs are already normalized (lowercase, digits, no separators except
  // they encode specials), so simple capitalization of the first char works
  // for our curated set. Digits are prefixed... but none of ours start w/ one.
  return "si" + slug.charAt(0).toUpperCase() + slug.slice(1);
}

function getIcon(slug: string): SiIcon | null {
  const mod = simpleIcons as unknown as Record<string, SiIcon | undefined>;
  const direct = mod[slugToExport(slug)];
  if (direct && typeof direct.path === "string") return direct;
  return null;
}

function pascal(key: string): string {
  return key
    .split("-")
    .map((p) => p.charAt(0).toUpperCase() + p.slice(1))
    .join("");
}

function componentName(key: string): string {
  return `${pascal(key)}Icon`;
}

function escapePath(d: string): string {
  // Path data is plain ASCII (commands + numbers); only need to guard quotes.
  return d.replace(/\\/g, "\\\\").replace(/"/g, '\\"');
}

function markSource(key: string, icon: SiIcon): string {
  const name = componentName(key);
  return `// AUTO-GENERATED by scripts/generate.ts — do not edit by hand.
// Source: Simple Icons (CC0) — "${icon.title}" (slug: ${icon.slug}).
// The trademark belongs to its owner; only the CC0 SVG path is shipped here.
import type { ComponentType } from "react";

const PATH =
  "${escapePath(icon.path)}";

export interface BrandIconProps {
  className?: string;
  size?: number;
}

export const ${name}: ComponentType<BrandIconProps> = ({ className, size = 24 }) => (
  <svg
    viewBox="0 0 24 24"
    width={size}
    height={size}
    className={className}
    fill="currentColor"
    role="img"
    aria-hidden="true"
  >
    <path d={PATH} />
  </svg>
);

${name}.displayName = "${name}";
`;
}

function main(): void {
  if (existsSync(MARKS_DIR)) rmSync(MARKS_DIR, { recursive: true, force: true });
  mkdirSync(MARKS_DIR, { recursive: true });

  const included: { key: string; title: string; slug: string; component: string }[] = [];
  const skipped: { key: string; slug: string }[] = [];

  for (const [key, slug] of Object.entries(CURATED)) {
    const icon = getIcon(slug);
    if (!icon) {
      skipped.push({ key, slug });
      continue;
    }
    writeFileSync(join(MARKS_DIR, `${key}.tsx`), markSource(key, icon), "utf8");
    included.push({ key, title: icon.title, slug: icon.slug, component: componentName(key) });
  }

  // Barrel for the marks: component exports, the key->component map, and the manifest.
  const lines: string[] = [];
  lines.push("// AUTO-GENERATED by scripts/generate.ts — do not edit by hand.");
  lines.push('import type { ComponentType } from "react";');
  lines.push('import type { BrandIconProps } from "./github";');
  for (const m of included) {
    lines.push(`import { ${m.component} } from "./${m.key}";`);
  }
  lines.push("");
  for (const m of included) {
    lines.push(`export { ${m.component} } from "./${m.key}";`);
  }
  lines.push('export type { BrandIconProps } from "./github";');
  lines.push("");
  lines.push("export interface BrandIconManifestEntry {");
  lines.push("  /** Kebab key the consumer types: <Icon name=\"github\" />. */");
  lines.push("  name: string;");
  lines.push("  /** Human-readable brand title. */");
  lines.push("  title: string;");
  lines.push("  /** Originating Simple Icons slug (CC0 source). */");
  lines.push("  slug: string;");
  lines.push("}");
  lines.push("");
  lines.push("/** Curated marks keyed by the name consumers resolve them under. */");
  lines.push("export const curatedMarks: Record<string, ComponentType<BrandIconProps>> = {");
  for (const m of included) {
    lines.push(`  "${m.key}": ${m.component},`);
  }
  lines.push("};");
  lines.push("");
  lines.push("/** Catalog of every curated mark (for icon pickers, e.g. fancy-cms). */");
  lines.push("export const curatedManifest: BrandIconManifestEntry[] = [");
  for (const m of included) {
    lines.push(`  { name: "${m.key}", title: ${JSON.stringify(m.title)}, slug: "${m.slug}" },`);
  }
  lines.push("];");
  lines.push("");

  writeFileSync(join(MARKS_DIR, "index.ts"), lines.join("\n"), "utf8");

  console.log(`fancy-brand-icons: generated ${included.length} marks into src/marks/`);
  console.log("included:", included.map((m) => m.key).join(", "));
  if (skipped.length) {
    console.log("skipped (not found in simple-icons):", skipped.map((s) => `${s.key}(${s.slug})`).join(", "));
  } else {
    console.log("skipped: none");
  }
}

main();
